### ISSUE TITLE
MN -> PDF: Remove duplicate part number from main title in front page, BSI PDF

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#88]
*In relation https://github.com/metanorma/metanorma-bsi/issues/30*

There are several documents that have duplicate part number in main title.
(Also there is duplicate m-dashes.)

From *bs-8887-220*:
![issue7-generated](https://user-images.githubusercontent.com/33627611/129299312-8c4152c2-f796-4c82-abb3-ad182554d48f.PNG)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/129595123-87b3d0d2-c2c5-47a6-a308-bc49a4d3b3e1.png)

**Comment by manuel489** [comment]
@Intelligent2013 the double m-dash issue is still present in *bs-8887-1-2006*:

![cap1](https://user-images.githubusercontent.com/33627611/129719463-41333284-a46b-45af-b482-86a202cd99b3.PNG)

**Comment by Intelligent2013** [comment]
There was complicated logic in title's displaying... Fixed:
![image](https://user-images.githubusercontent.com/5559926/130132766-5b74bb73-3246-408b-a075-5cff9bad7ee4.png)

**Comment by manuel489** [comment]
@Intelligent2013, this issue persists for *bs-8887-1-2006*:
![cap1](https://user-images.githubusercontent.com/33627611/130325633-feba33cf-7e1a-4f27-9cb5-fad6b26fa409.PNG)

Maybe we haven't applied this solution in global scope?

**Comment by manuel489** [comment]
I'm still getting the issue even when I fetch directly from *metanorma-bsi* repository.
So I'm going to wait until next release to check again.

**Comment by manuel489** [comment]
Fix confirmed, closing.
